### ISSUE TITLE
Spam accept

### ISSUE THREAD

**Issue by ghost** [Polymeta/WonderTrade#2]
Not sure how much of a issue this really is.

But for servers with no cool down on WonderTrade, players can select the pokemon they want to trade & when the chat message pops up, instead of clicking on the accept button, if they click slightly above it, they can just keep spamming the wt trade command over & over without having to re-select the pokemon they want to trade. 

Essential it spams chat but also gives players advantages over others as they don't need to go through the selection process again.

**Comment by Polymeta** [comment]
Yeah that's true, that's kind of a sideeffect of not using cooldowns, isn't it?

All the clicking does is run the following command: `/wt <slot> --confirm` which can be "spammed" even without a chat prompt in theory, but that's why the cooldown is in place, so player's can't abuse it to the extend you described, unless I missed something.

**Comment by ghost** [comment]
Nah didn't miss anything. Yh enabling cool down solves it, kinda dumb I didn't think to enable it in the first place. Cheers Polymeta
